Redis:
  host: localhost
  port: 6379
  user:
  pass:
Cassandra:
  host: localhost
  port: 9042
  user:
  pass:
  keyspace: mapper
MongoDB:
  host: localhost
  port: 27017
  user:
  pass:
  database: mapper
MySQL:
  host: localhost
  port: 3306
  user: root
  pass: root
  database: mapper