Redis:
  host: 192.168.0.125
  port: 6379
  user:
  pass:
Cassandra:
  host: 192.168.0.125,192.168.0.122
  port: 9042
  user:
  pass:
  database:
MongoDB:
  host: 192.168.0.125
  port:
  user:
  pass:
  database:
MySQL:
  host: 192.168.0.125
  port: 3306
  user:
  pass:
  database: